import 'server-only';
import { eq, asc, inArray } from 'drizzle-orm';
import { db } from '@/lib/db/client';
import { deals as dealsTable, generatedDemos, leads as leadsTable, audits as auditsTable } from '@/lib/db/schema';
import { AV } from '@/lib/data';
import { DEMO_STATUS, relativeTime } from '@/lib/data/format';
import type { Demo, Deal } from '@/lib/data/types';
import { USE_DB } from './config';

// Standard improvements every AI redesign delivers — descriptive product copy, not per-lead fabricated data.
const REDESIGN_CHANGES = [
  'Rebuilt mobile-first with a clear above-the-fold call-to-action',
  'Modern, on-brand visual design in place of the dated template',
  'Trust signals (reviews / credentials) and a simple contact-or-booking path',
  'Faster, cleaner layout focused on conversion',
];

// DB mode has no `demos` rows (that table is the demo-mode mock). The live Demos screen is derived from
// generated_demos (the real AI output) joined with the lead + its audit, so a generated demo shows up here
// immediately. Status comes from the lead's demo lifecycle; a not-yet-triaged demo defaults to "review".
function buildDemoRow(
  l: typeof leadsTable.$inferSelect,
  a: typeof auditsTable.$inferSelect | undefined,
  gen: typeof generatedDemos.$inferSelect,
): Demo {
  const status = l.demo && DEMO_STATUS[l.demo] ? l.demo : 'review';
  const st = DEMO_STATUS[status];
  const score = l.score;
  const probs = (a?.problems as string[] | undefined) ?? [];
  return {
    id: 'demo-' + l.id,
    leadId: l.id,
    business: l.company,
    industry: l.industry,
    city: l.city,
    url: l.url,
    oldScore: l.site,
    newScore: l.score,
    status,
    statusLabel: st.label,
    statusCls: st.cls,
    agents: ['atlas', 'nova', 'iris', 'kira'],
    generated: gen.updatedAt ? relativeTime(Math.floor(new Date(gen.updatedAt).getTime() / 1000)) : 'today',
    demoUrl: '/demo/' + l.id,
    clientStatus: st.label,
    value: l.value,
    changes: probs.length ? probs.slice(0, 5) : REDESIGN_CHANGES,
    notes: (a?.summary as string | undefined) || 'Generated by the design room from the audit and brand direction.',
    checklist: {
      'Responsive layout': true,
      'Clear primary CTA': true,
      'Strong hero section': true,
      'Trust elements': score > 82,
      'Contact / booking form': true,
      'SEO basics': score > 80,
      'Brand consistency': score > 85,
    },
    outreach: {
      subject: `A new homepage concept for ${l.company}`,
      body: `Hi ${l.company.split(' ')[0]} team — we rebuilt your homepage as a working demo (no charge, no obligation). It loads fast, works on mobile, and is built to convert. Take a look and tell us what you think.`,
    },
  };
}

export async function getDemos(): Promise<Demo[]> {
  if (!USE_DB) return AV.demos;
  const gens = await db.select().from(generatedDemos).where(eq(generatedDemos.status, 'ready'));
  if (gens.length === 0) return [];
  const ids = gens.map((g) => g.leadId);
  const [leadRows, auditRows] = await Promise.all([
    db.select().from(leadsTable).where(inArray(leadsTable.id, ids)),
    db.select().from(auditsTable).where(inArray(auditsTable.leadId, ids)),
  ]);
  const auditBy = new Map(auditRows.map((a) => [a.leadId, a]));
  const genBy = new Map(gens.map((g) => [g.leadId, g]));
  return leadRows
    .map((l) => { const g = genBy.get(l.id); return g ? buildDemoRow(l, auditBy.get(l.id), g) : null; })
    .filter((d): d is Demo => d !== null)
    .sort((x, y) => (x.id < y.id ? -1 : 1));
}

export async function demoByLead(leadId: string): Promise<Demo | undefined> {
  if (!USE_DB) return AV.demoByLead(leadId);
  const [gen] = await db.select().from(generatedDemos).where(eq(generatedDemos.leadId, leadId)).limit(1);
  if (!gen || gen.status !== 'ready') return undefined;
  const [l] = await db.select().from(leadsTable).where(eq(leadsTable.id, leadId)).limit(1);
  if (!l) return undefined;
  const [a] = await db.select().from(auditsTable).where(eq(auditsTable.leadId, leadId)).limit(1);
  return buildDemoRow(l, a, gen);
}

export async function getDeals(): Promise<Deal[]> {
  if (!USE_DB) return AV.deals;
  return db.select().from(dealsTable).orderBy(asc(dealsTable.id));
}

export async function getDeal(id: string): Promise<Deal | undefined> {
  if (!USE_DB) return AV.deals.find((d) => d.id === id);
  const [row] = await db.select().from(dealsTable).where(eq(dealsTable.id, id)).limit(1);
  return row ?? undefined;
}

export async function dealByLead(leadId: string): Promise<Deal | undefined> {
  if (!USE_DB) return AV.dealByLead(leadId);
  const [row] = await db.select().from(dealsTable).where(eq(dealsTable.leadId, leadId)).limit(1);
  return row ?? undefined;
}
